services:
    fp.swfupload.form.type.swfupload_file:
        class:                          Fp\SwfuploadBundle\Form\Type\SwfuploadFileType
        arguments:
            -                           %kernel.debug%
        tags:
            -                           { name: form.type, alias: swfupload_file }

    fp.swfupload.form.type.jquery_file:
        class:                          Fp\SwfuploadBundle\Form\Type\JqueryFileType
        tags:
            -                           { name: form.type, alias: jquery_file }
            
    fp.swfupload.twig.swfupload_extension:
        class:                          Fp\SwfuploadBundle\Twig\SwfuploadExtension
        public:                         false
        tags:
            -                           { name: twig.extension }
